### PR TITLE
Got rid of redundant json dumps

### PR DESCRIPTION
**Pull request by GlaciErrDev**

### CODE REVIEW

**Comment by denismakogon** [comment]
+1

**Comment by 0lvin** [comment]
+1

**Comment by yoramw** [comment]
+1

**Comment by pacogomez** [comment]
the call to dumps is required to convert from unicode to ascii, otherwise the manager will reply with a validation error:
2015-08-12 02:26:37,564 | DEBUG | requests.packag | connectionpool  | _make_reques | "PUT /deployments/helloworld-2 HTTP/1.1" 400 1283
2015-08-12 02:26:37,570 | DEBUG | pyvcloud        | __init__        | _log_respons | [400]  Validation error: {u'vcloud_vdc': u'vdc1', u'vcloud_password':

} is not of type 'string'

Failed validating 'type' in schema['properties']['inputs']:
    {'type': 'string'}

On instance['inputs']:
    {u'auto_generate_ssh_keys': True,

**Comment by pacogomez** [comment]
please note that this won't work with current version of score on prod

**Pull request merged**
