### PR TITLE
'firewall add' and 'firewall delete' commands

### PR DESCRIPTION
**Pull request by pedantic-git**
This pull request adds the 'firewall add' and 'firewall delete' commands, modelled after the 'nat add' and 'nat delete' commands and using the existing functions in pyvcloud to drive the firewall.

It also fixes a minor bug where some 500 errors in XML format were being treated as JSON and crashing the error handler.

### CODE REVIEW

**Comment by pacogomez** [comment]
looks good. Thanks!

**Comment by pacogomez** [comment]
I'm going to publish vca-cli with this changes on pip as version 16. Can you please provide an example 'ferules.yml' file?
thanks

**Comment by pedantic-git** [comment]
Oh that's a good point! I don't have one to hand, but it should be something like:

```yaml
---
Firewall_rules:
  - protocol:    tcp
    dest_port:   80
    dest_ip:     192.168.0.0/16
    source_port: any
    source_ip:   10.19.1.0/24
  - protocol:    udp
    dest_port:   53
    dest_ip:     any
    source_port: any
    source_ip:   any
```

**Comment by pedantic-git** [comment]
You can also combine nat_rules.yml and fw_rules.yml into a single file, since they only check the `NAT_rules` and `Firewall_rules` sections of the file, respectively.

**Pull request merged**
